run:
	g++ -std=c++23 -g -municode -Wall main.cpp -o listfile.exe
	./listfile.exe "C:\\Users\\a\\Downloads"

build:
	g++ -std=c++23 -g -municode -Wall main.cpp -o listfile.exe

clean:
	del listfile.exe