run:
	g++ -std=c++23 -Wall -municode -g main.cpp -o timep.exe
	./timep.exe

build_exp:
	g++ -std=c++23 -Wall -g exp.cpp -o exp.exe

build:
	g++ -std=c++23 -Wall -municode -g main.cpp -o timep.exe

clean:
	del timep.exe